services:
  app:
    # archlinux doesn't support arm64 yet
    # so it's forced to use amd64
    platform: linux/amd64
    cpus: 2
    mem_limit: 4g
    mem_swappiness: 20g
    build:
      context: .
      dockerfile: Dockerfile.app
      # bulld time args
      args:
        USERNAME: ${USERNAME}
        HELIX_VERSION: ${HELIX_VERSION}
        USER_GID: ${USER_GID}
        USER_UID: ${USER_UID}
        DOTFILES_REPO: ${DOTFILES_REPO}
        DOTFILES_SETUP_SH: ${DOTFILES_SETUP_SH}
        DOCKER_BUILDKIT: 1

    env_file:
      # relative path to .env file
      - .env

    volumes:
      - ../:/workspace
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    networks:
      default:
        ipv4_address: ${NETWORK_BITS}.10

networks:
  default:
    external: true
    name: ${SUBNET_NAME}
# networks:
#   default:
#     name: ${DEFAULT_SUBNET}
#     driver: bridge
#     ipam:
#       config:
#         - subnet: ${DEFAULT_SUBNET_CIDR}
